server:
  port: 8082

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5434/event_db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

internal:
  trusted-services:
    booking-service: ${BOOKING_INTERNAL_API_KEY}