server:
  port: 8084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5436/notification_db
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: ${MAIL_HOST:smtp.mail.ru}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

email:
  executor:
    core-pool-size: 4
    max-pool-size: 16
    queue-capacity: 200
  check-delay-ms: 10000

jwt:
  secret: ${JWT_SECRET:}
  expiration: 86400000

telegram:
  bot-username: ${BOT_NAME:}

internal:
  secret: ${NOTIFICATION_INTERNAL_API_KEY:}
  trusted-services:
    telegram-bot: ${BOT_INTERNAL_API_KEY:}

booking-service:
  base-url: http://booking-service:8083

booking-ui:
  base-url: ${BOOKING_UI_BASE_URL:http://localhost:3000}