server {
    listen 8080;

    resolver 127.0.0.11 valid=10s;

    add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    if ($request_method = OPTIONS) {
        return 204;
    }

    location /auth/ {
        set $upstream_auth auth-service:8081;
        proxy_pass http://$upstream_auth$request_uri;
    }

    location /events {
        set $upstream_event event-service:8082;
        proxy_pass http://$upstream_event$request_uri;
    }

    location /admin/events {
        set $upstream_event event-service:8082;
        proxy_pass http://$upstream_event$request_uri;
    }

    location /bookings {
        set $upstream_booking booking-service:8083;
        proxy_pass http://$upstream_booking$request_uri;
    }

    location /admin/bookings {
        set $upstream_booking booking-service:8083;
        proxy_pass http://$upstream_booking$request_uri;
    }

    location /user/ {
        set $upstream_notification notification-service:8084;
        proxy_pass http://$upstream_notification$request_uri;
    }
}