server:
  port: 8083

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5435/booking_db
    username: postgres
    password: postgres

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000